# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_graph_components
#'
#' Calculates the number and size of graph components.
#'
#' @param graph graph to be analysed.
#' @return \code{Rcpp::IntegerVector} containing the graph component sizes in
#' descending order.
#'
#' @noRd
rcpp_graph_components <- function(graph) {
    .Call(`_graphreport_rcpp_graph_components`, graph)
}

